---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(data.table)
source('/home/sukhyun/project/bike_sharing_demand/R/data_cleansing.R')
```

### 1. EDA
#### 1.1 Distribution of y
```{r, echo=FALSE, fig.height=3, fig.width=9}
par(mfrow = c(1,3), mar=c(4,4,4,4))
for (i in c('casual', 'registered', 'count')) {
  m <- round(mean(data_tr[[i]]))
  v <- round(var(data_tr[[i]]))
  m <- paste('mean :', m)
  v <- paste('var :', v)
  hist(
    data_tr[[i]], xlim = c(0, 1000), main = title(c(i,m,v)),
    xlab = '', probability = T, # ylim = c(0,6000)
  )
}
```
<br>  
<br>  

#### 1.2 Trend
```{r, echo=FALSE, fig.height=3, fig.width=9}
par(mfrow = c(1,3), mar=c(4,4,4,4))
for (i in c('casual', 'registered', 'count')) {
  plot(
    data_tr$datetime, data_tr[[i]], xlab = 'datetime', ylab = i
  )
}
```
<br>  
<br>  

#### 1.3 Trend hour
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.height=3, fig.width=3}
# profile by day
par(mfrow = c(1,1), mar=c(4,4,2,1))
plot(
  data_tr$hour, data_tr$count, 'n', xlab = 'hour', ylab = 'count', main='count'
)
f <- function(d) {
  lines(d$hour, d$count, col=alpha(1, 0.3))
  invisible()
}
tmp <- by(data_tr, data_tr$date, f)
```

```{r, echo=FALSE, fig.height=6, fig.width=6}
profile_hour <- function(data, figsize = c(1,2), group, y) {
  par(mfrow = figsize)
  for (i in unique(data[[group]])) {
    plot(
      data$hour, data[[y]], 'n',
      main = paste(group, i, sep = ' : '),
      xlab = 'hour', ylab = 'count'
    )
    by(
      data[data[[group]] == i],
      data[data[[group]] == i]$date,
      function(d) lines(d$hour, d[[y]], col=alpha(1, 0.3))
    )
  }
  invisible()
}
profile_hour(data_tr, c(2,2), 'season', 'count')
# profile_hour(data_tr, c(2,4), 'weekdays', 'count')
# profile_hour(data_tr, c(2,2), 'weather', 'count')
# profile_hour(data_tr, c(1,2), 'weekend', 'count')
```
```{r, echo=FALSE, fig.height=3, fig.width=6}
profile_hour(data_tr, c(1,2), 'holiday', 'count')
```
```{r, echo=FALSE, fig.height=3, fig.width=6}
profile_hour(data_tr, c(1,2), 'workingday', 'count')
```
```{r, echo=FALSE, fig.height=6, fig.width=12}
profile_hour(data_tr, c(2,4), 'weekdays', 'count')
```
```{r, echo=FALSE, fig.height=3, fig.width=6}
profile_hour(data_tr, c(1,2), 'weekend', 'count')
```
<br>  
<br>  

### 2. overdispersion
#### 2.1 dispersion statistic
```{r, warning=FALSE, message=FALSE}
form <- count ~ workingday + weather + 
  temp + humidity + windspeed + hour + I(hour^2)
poi_mod <- glm(formula = form, data = data_tr, family = poisson)

pchi2 <- sum(residuals(poi_mod, type = 'pearson')^2)
disp_stat <- pchi2/poi_mod$df.residual
disp_stat
```
<br>  
<br>  

#### 2.1 observed vs expected counts
```{r, fig.width=6, fig.height=4}
obs_counts <- table(data_tr$count)[1:100]
exp_probs <- sapply(1:100, function(x) dpois(x, poi_mod$fitted.values))
exp_counts <- round(apply(exp_probs, 2, sum))

# table
# rbind(obs_counts, exp_counts)

# plot
plot(1:100, obs_counts, pch = 19, col = 'red', xlab = 'count')
lines(1:100, obs_counts, col = 'red')
points(1:100, exp_counts, pch = 19, col = 'blue')
lines(1:100, exp_counts, col = 'blue')
legend('topright', c('obs', 'exp'), pch=19, col=c('red', 'blue'))
```
```{r}
```


